// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emqnvstmldyweuptmptz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcW52c3RtbGR5d2V1cHRtcHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTA2NjgsImV4cCI6MjA4ODk4NjY2OH0.XpCrBssTW82znWzQ18PDpLRoXHJ96ph8HrQ66dBZiJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});